#!/usr/bin/env bash

sink_name=$(pactl get-default-sink)
source_name=$(pactl get-default-source)

incr="+5%"
decr="-5%"

msgTag="myvolume"

case "$1" in
"up")
	pactl set-sink-volume $sink_name $incr
	volume="$(pactl get-sink-volume $sink_name | tail -2 | awk '{print $5}' | sed 's/[^0-9]*//g')"
	# Show the volume notification
	dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
		-h int:value:"$volume" "Volume: ${volume}%"
	;;
"down")
	pactl set-sink-volume $sink_name $decr
	volume="$(pactl get-sink-volume $sink_name | tail -2 | awk '{print $5}' | sed 's/[^0-9]*//g')"
	# Show the volume notification
	dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
		-h int:value:"$volume" "Volume: ${volume}%"
	;;
"toggle")
	pactl set-sink-mute $sink_name "toggle"
	mute="$(pactl get-sink-mute $sink_name | awk '{print $2}')"
	# toggle led on mute key
	case $mute in
	"no")
		echo "0" >/sys/devices/platform/thinkpad_acpi/leds/platform\:\:mute/brightness
		;;
	"yes")
		echo "1" >/sys/devices/platform/thinkpad_acpi/leds/platform\:\:mute/brightness
		;;
	esac
	# Show the sound muted notification
	dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Mute: $mute"
	;;
"umute")
	pactl set-sink-mute $sink_name "0"
	;;
"mic toggle")
	pactl set-source-mute $source_name "toggle"
	mute="$(pactl get-source-mute 1 | awk '{print $2}')"
	# toggle led on mic mute key
	case $mute in
	"no")
		echo "0" >/sys/devices/platform/thinkpad_acpi/leds/platform\:\:micmute/brightness
		;;
	"yes")
		echo "1" >/sys/devices/platform/thinkpad_acpi/leds/platform\:\:micmute/brightness
		;;
	esac
	# Show the sound muted notification
	dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Mic Mute: $mute"
	;;
esac
