#! /usr/bin/env bash

kitty @ set-tab-title music
kitty @ set-window-title cover
kitty @ new-window --title ncmpcpp ncmpcpp
# kitty @ resize-window --increment 93
source "$HOME/scripts/music/album_cover.sh"
