#! /usr/bin/env bash

kitty @ set-enabled-layouts splits
kitty @ set-tab-title music
kitty @ set-window-title cover
kitty @ launch --location first --title ncmpcpp ncmpcpp
# kitty @ set-enabled-layouts splits
# kitty @ set-tab-title music
# kitty @ set-window-title cover
# kitty @ launch --location hsplit --title ncmpcpp ncmpcpp
source "$HOME/scripts/music/album_cover.sh"
