#!/usr/bin/env bash

case "$BLOCK_BUTTON" in
    4) st -e "$EDITOR" "$0" ;;
esac

incr=10
volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//')
mute=$(amixer get Master | tail -n 1 | grep -o -P '\[on\]|\[off\]')
muteMic=$(amixer get Capture | tail -n 1 | grep -o -P '\[on\]|\[off\]')

# kill -(34 + signal number in dwmblocks-async config.h)
refreshDWMBlocks="kill -35 $(pidof dwmblocks) 2>/dev/null"

case "$1" in
"up")
  amixer --quiet set Master "$(($volume + $incr))%"
  eval $refreshDWMBlocks
	;;

"down")
  amixer --quiet set Master "$(($volume - $incr))%"
  eval $refreshDWMBlocks
	;;

"toggle")
  amixer set Master toggle
  eval $refreshDWMBlocks
  ;;

"mic-toggle")
  amixer set Capture toggle
  eval $refreshDWMBlocks
  ;;

"get")
  volume = $(eval $volumeCMD)
  echo "S ${mute} ${volume}%"
  exit 0
  ;;
esac

volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//')
mute=$(amixer get Master | tail -n 1 | grep -o -P '\[on\]|\[off\]')
muteMic=$(amixer get Capture | tail -n 1 | grep -o -P '\[on\]|\[off\]')

msgTag="myvolume"
# Show the volume notification
dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
  -h int:value:$volume "Volume: ${volume}% | Mute: $mute | Mic: $muteMic"
