#!/usr/bin/env bash

toggle_wifi ()
{
  status="$(nmcli r wifi)"
  if [ "$status" == "enabled" ]; then
    nmcli radio wifi off
    dunstify -u low "WiFi: [off]"
  else
    nmcli radio wifi on
    dunstify -u low "WiFi: [on]"
    sleep 5
  fi
}

# signal number + 34
case "$BLOCK_BUTTON" in
    1) "$TERMINAL" -e nmtui; kill -37 $(pidof dwmblocks) ;;
    3) toggle_wifi ;;
    4) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

essid=$(nmcli -g active,ssid dev wifi | grep '^yes' | cut -d: -f2)

if [ -z "${essid}" ]; then
  essid="Disconnected"
fi

echo "${essid}"
