#!/usr/bin/env bash

#
# Set brightness with light, but never go below 1 (as that's "off").
#

round() {
  printf "%.${2}f" "${1}"
}

# Increment to use.
incr=10

msgTag="myBrightness"

cur=$(round $(light) 0)

# kill -(34 + signal number in dwmblocks-async config.h)
refreshDWMBlocks="kill -36 $(pidof dwmblocks) 2>/dev/null"

case "$1" in
	"up")
		if [[ $(($cur + $incr)) -ge 100 ]]; then
			light -S 100
		else
      light -S $(($cur + $incr))
		fi
    eval "$refreshDWMBlocks"
	;;
	"down")
		if [[ $(($cur - $incr)) -le $incr ]]; then
			light -S $incr
		else
      light -S $(($cur - $incr))
		fi
    eval "$refreshDWMBlocks"
	;;
	"get")
    echo "L $cur%"
	;;
	*)
		echo "Unsupported: \"$1\""
		exit 1
esac

brightness=$(round $(light) 0)

dunstify -a "changeBrightness" -u low -i brightness -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$brightness" "Brightness: ${brightness}%"
